### ISSUE TITLE
Turbo Unlock for X99 G5350 Ver 1.0 Motherboard

### ISSUE THREAD

**Issue by Meridian8** [miyconst/miyconst.github.io#1]
Hi Miyconst, 

I have enjoyed all the info and videos that you have created and I think you have been a great help to many and I thank you for your efforts. 

I was recently given a X99 G5350 Ver 1.0 motherboard by a friend as per the picture below. This motherboard is said to be able to accept both Ddr3 and Ddr4 ram depending on which cpu you use. I wish to perform turbo unlock but there doesn't seem to be much info online about this motherboard.

Any idea which turbo unlock bios is compatible/suitable for this motherboard? Also, what cpu do you recommend to use for gaming on this motherboard.

Many thanks in advance... 

![Screenshot_20230831_150608](https://github.com/miyconst/miyconst.github.io/assets/143779815/d85fa131-d132-46c1-a481-c351483c607a)

**Comment by miyconst** [comment]
Unfortunately this is one of those noname motherboards that may come with different (random) hardware configuration. I didn't test the motherboard myself, thus can't guarantee any BIOS compatibility, but if you are willing to risk, you can try Huananzhi BIOS with the same chipset.

**Comment by Meridian8** [comment]
Noted... So does this mean that I have to unlock using the old method as per your old video... which is to modify/update the bios by deleting the 06F2 patch via MMTool and then inject a new FFS driver from ur archive via UEFITool and flash the modified bios?

**Comment by miyconst** [comment]
>Noted... So does this mean that I have to unlock using the old method as per your old video...

Yes.

**Comment by Meridian8** [comment]
Sorry, I just want to clarify.... to be safe and not take risk, i should use the old method and inject the FFS driver... Correct?

**Comment by miyconst** [comment]
>to be safe and not take risk, i should use the old method and inject the FFS driver... Correct?

That's correct, but there is no such thing as "safe" when it comes to BIOS modding. Something may go wrong even if you do everything right.

**Comment by Meridian8** [comment]
Duly noted... Thank you for your time and advice
